//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.ARTICULO1 = new HashSet<ARTICULO>();
            this.ARTICULO11 = new HashSet<ARTICULO>();
            this.ARTICULO12 = new HashSet<ARTICULO>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string CentroOperativo { get; set; }
        public Nullable<short> CtrlStock { get; set; }
        public Nullable<decimal> StockMaximo { get; set; }
        public Nullable<decimal> StockMinimo { get; set; }
        public string UnidadMedida { get; set; }
        public string AlicuotaIVA { get; set; }
        public string AlicuotaPercepcionDGR { get; set; }
        public string Origen { get; set; }
        public string Ubicacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> AlicuotaImpInterno { get; set; }
        public decimal UnidadMedidaEquiv { get; set; }
        public Nullable<int> Redondeo { get; set; }
        public Nullable<int> ActualContabilidadCosto { get; set; }
        public Nullable<int> ActualStock { get; set; }
        public string AlicuotaPercepcion { get; set; }
        public Nullable<int> ActualizaPrecio { get; set; }
        public Nullable<int> Visible { get; set; }
        public string Material { get; set; }
        public string Plano { get; set; }
        public Nullable<decimal> LargoCorte { get; set; }
        public Nullable<decimal> AnchoCorte { get; set; }
        public Nullable<decimal> FactorConversion { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string ArticuloAnterior { get; set; }
        public string ArticuloPosterior { get; set; }
        public Nullable<int> TipoProduccion { get; set; }
        public Nullable<int> EmiteOrdenProduccion { get; set; }
        public Nullable<int> Repuesto { get; set; }
        public Nullable<decimal> AnticipacionProduccion { get; set; }
        public Nullable<decimal> LoteEconomico { get; set; }
        public Nullable<decimal> ImporteImpInterno { get; set; }
        public string Texto1 { get; set; }
        public string Texto2 { get; set; }
        public string Texto3 { get; set; }
        public string Texto4 { get; set; }
        public string Texto5 { get; set; }
        public Nullable<decimal> Importe1 { get; set; }
        public Nullable<decimal> Importe2 { get; set; }
        public Nullable<decimal> Importe3 { get; set; }
        public Nullable<int> Marca1 { get; set; }
        public Nullable<int> Marca2 { get; set; }
        public Nullable<int> Marca3 { get; set; }
        public Nullable<System.DateTime> Fecha1 { get; set; }
        public Nullable<System.DateTime> Fecha2 { get; set; }
        public string UnidadConversion { get; set; }
        public string ArticuloBase { get; set; }
        public string Texto6 { get; set; }
        public string Texto7 { get; set; }
        public string Texto8 { get; set; }
        public Nullable<decimal> Importe4 { get; set; }
        public Nullable<decimal> Importe5 { get; set; }
        public Nullable<decimal> Importe6 { get; set; }
        public Nullable<decimal> Importe7 { get; set; }
        public Nullable<decimal> Importe8 { get; set; }
        public Nullable<int> ArticuloInterno { get; set; }
        public Nullable<decimal> PorcentajeRecupero { get; set; }
        public Nullable<decimal> PorcentajeDerecho { get; set; }
        public Nullable<decimal> Kilos { get; set; }
        public string ArticuloPrincipioActivo { get; set; }
        public Nullable<int> Fitosanitario { get; set; }
        public byte[] C_RVersion { get; set; }
        public Nullable<int> ValidaValeCompra { get; set; }
        public Nullable<int> CalculaCantidadEquiv { get; set; }
        public Nullable<decimal> CoeficienteReintegro { get; set; }
        public string CodigoUnidadMedidaEquiv { get; set; }
        public Nullable<int> CalculaPercepcionIVA { get; set; }
        public Nullable<int> CalculaPercepcionIIBB { get; set; }
        public Nullable<int> DiasVencimiento { get; set; }
        public string NombreFantasia { get; set; }
        public Nullable<int> SemillaFiscalizada { get; set; }
        public Nullable<int> ArticuloCategoria { get; set; }
        public string ArticuloVariedad { get; set; }
        public string Grano { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO1 { get; set; }
        public virtual ARTICULO ARTICULO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO11 { get; set; }
        public virtual ARTICULO ARTICULO3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO12 { get; set; }
        public virtual ARTICULO ARTICULO4 { get; set; }
    }
}
