//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado_Pedido_Cuerpo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estado_Pedido_Cuerpo()
        {
            this.Orden_Produccion_Parte = new HashSet<Orden_Produccion_Parte>();
            this.OrdenProduccion_Cuerpo = new HashSet<OrdenProduccion_Cuerpo>();
            this.Pedido_Cuerpo = new HashSet<Pedido_Cuerpo>();
            this.TT_OrdenProduccion_Cuerpo = new HashSet<TT_OrdenProduccion_Cuerpo>();
            this.TT_Pedido_Cuerpo = new HashSet<TT_Pedido_Cuerpo>();
        }
    
        public string ID { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Produccion_Parte> Orden_Produccion_Parte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenProduccion_Cuerpo> OrdenProduccion_Cuerpo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Cuerpo> Pedido_Cuerpo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_OrdenProduccion_Cuerpo> TT_OrdenProduccion_Cuerpo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_Pedido_Cuerpo> TT_Pedido_Cuerpo { get; set; }
    }
}
