//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESOMERCADERIACUERPO_MEMOS
    {
        public int ID { get; set; }
        public Nullable<int> Ingreso_ID { get; set; }
        public string Articulo_ID { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<decimal> CostoOriginal { get; set; }
        public Nullable<decimal> PrecioOriginal { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
