//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESOMERCADERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGRESOMERCADERIA()
        {
            this.INGRESOMERCADERIACUERPO = new HashSet<INGRESOMERCADERIACUERPO>();
        }
    
        public long ID { get; set; }
        public Nullable<int> Movimiento_ID { get; set; }
        public Nullable<int> Proveedor_ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
        public string NumeroComprobante { get; set; }
        public string LetraComprobante { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Guardado { get; set; }
        public Nullable<int> MedioPago { get; set; }
        public Nullable<int> Empleado_ID { get; set; }
    
        public virtual MOVIMIENTOS MOVIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGRESOMERCADERIACUERPO> INGRESOMERCADERIACUERPO { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual MEDIOPAGO MEDIOPAGO1 { get; set; }
    }
}
