//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOCUENTACORRIENTECUERPO
    {
        public long ID { get; set; }
        public long MovimientoCuentaCorriente_ID { get; set; }
        public long Movimiento_ID { get; set; }
        public Nullable<decimal> ImporteAfectado { get; set; }
    
        public virtual MOVIMIENTOCUENTACORRIENTE MOVIMIENTOCUENTACORRIENTE { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
