//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOCUENTACORRIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIMIENTOCUENTACORRIENTE()
        {
            this.MOVIMIENTOCUENTACORRIENTECUERPO = new HashSet<MOVIMIENTOCUENTACORRIENTECUERPO>();
        }
    
        public long ID { get; set; }
        public Nullable<int> Movimiento_ID { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<int> Tipo_Gasto_ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Observaciones { get; set; }
        public string Estado_ID { get; set; }
        public string NumeroComprobante { get; set; }
        public Nullable<int> MedioPago_ID { get; set; }
        public Nullable<long> CajaUsuario_ID { get; set; }
    
        public virtual MOVIMIENTOS MOVIMIENTOS { get; set; }
        public virtual Tipo_Gasto Tipo_Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOCUENTACORRIENTECUERPO> MOVIMIENTOCUENTACORRIENTECUERPO { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual MEDIOPAGO MEDIOPAGO { get; set; }
    }
}
