//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREA()
        {
            this.TAREACUERPO = new HashSet<TAREACUERPO>();
        }
    
        public long ID { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> OrdenadaPor_ID { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public Nullable<short> Prioridad_ID { get; set; }
        public Nullable<int> Clasificacion_ID { get; set; }
        public string Planteo { get; set; }
        public string Sugerencias_Planteo { get; set; }
        public string Acciones { get; set; }
        public string AnexosAltercados_Acciones { get; set; }
        public string ComentarioAprobacion { get; set; }
        public Nullable<short> PuntuacionAprobacion { get; set; }
        public Nullable<int> ReponsableAprobacion_ID { get; set; }
        public string Observaciones { get; set; }
        public Nullable<short> EstadoAprobacion { get; set; }
    
        public virtual TAREACLASIFICACION TAREACLASIFICACION { get; set; }
        public virtual TAREAPRIORIDAD TAREAPRIORIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREACUERPO> TAREACUERPO { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Empleados Empleados1 { get; set; }
        public virtual Empleados Empleados2 { get; set; }
        public virtual Empleados Empleados3 { get; set; }
    }
}
