//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET()
        {
            this.MOVIMIENTOCUENTACORRIENTECUERPO = new HashSet<MOVIMIENTOCUENTACORRIENTECUERPO>();
            this.TICKETCUERPO = new HashSet<TICKETCUERPO>();
            this.TICKETMEDIOPAGO = new HashSet<TICKETMEDIOPAGO>();
        }
    
        public long ID { get; set; }
        public string NumeroTicket { get; set; }
        public int Cliente_ID { get; set; }
        public int MedioPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Letra { get; set; }
        public Nullable<int> Movimiento_ID { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> ImporteAfectado { get; set; }
        public Nullable<decimal> Entregado { get; set; }
        public Nullable<long> CajaUsuario_ID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual MEDIOPAGO MEDIOPAGO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOCUENTACORRIENTECUERPO> MOVIMIENTOCUENTACORRIENTECUERPO { get; set; }
        public virtual MOVIMIENTOS MOVIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETCUERPO> TICKETCUERPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETMEDIOPAGO> TICKETMEDIOPAGO { get; set; }
    }
}
