//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOTEMA
    {
        public int ID { get; set; }
        public int Usuario { get; set; }
        public string Tema { get; set; }
    
        public virtual TEMA TEMA1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
