//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPedidos002
    {
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<long> PedidoID { get; set; }
        public Nullable<int> VendedorID { get; set; }
        public string Vendedor { get; set; }
        public Nullable<int> Zona_ID { get; set; }
        public string Zona { get; set; }
        public string EstadoPedido { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public string EstadoProductivo { get; set; }
        public string EstadoViaje { get; set; }
        public string EstadoEnvio { get; set; }
        public string EstadoEnvioPedido { get; set; }
        public string EstadoProductivoPedido { get; set; }
        public string NumeroPedido { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string Cliente { get; set; }
        public int CiudadID { get; set; }
        public string Ciudad { get; set; }
        public Nullable<decimal> CantidadOriginal { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
