//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCodin_Sinlacc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_OrdenProduccionParte
    {
        public long OrdenProdParteID { get; set; }
        public long OrdenProdCuerpoID { get; set; }
        public long OrdenProducionID { get; set; }
        public long NroPedido { get; set; }
        public string Numero_Pedido { get; set; }
        public string CodigoInsumo { get; set; }
        public string DescripcionInsumo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal CantidadProducida { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public string CodProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public int CodSeccion { get; set; }
        public string DescripcionSeccion { get; set; }
        public string Horas { get; set; }
        public string Minutos { get; set; }
        public Nullable<decimal> Avance { get; set; }
    }
}
